### ISSUE TITLE
RPC error responses print "Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by popiel** [popiel/Lacuna-Automation#5]
Whenever Lacuna gives an error response, "Inappropriate ioctl for device" is printed as the exception is generated.  This messes up the logs and is confusing.

**Comment by popiel** [comment]
This seems to only happen when the exception is not caught.  Inappropriate stringification?

**Comment by paulbort** [comment]
It's been ten months and many updates, is this still an issue?

**Comment by popiel** [comment]
Yes, it is still an issue.  It doesn't interfere with properly functioning scripts, and thus has not been a priority to fix.  (I also haven't logged into the game in about a month...)

**Comment by popiel** [comment]
I just fixed this.  Stringification now looks something like this:

LacunaRPCException 1011: Not enough energy in storage to build this.

Conversion to boolean is always true, and conversion to numeric yields the exceptions code number.
